### ISSUE TITLE
项目场景匹配，求合作

### ISSUE THREAD

**Issue by ToothlessOla** [zichengzichengzi/Scrap_Steel_Image_Dataset#3]
你好，我这边当前也是在做废钢回收场景的质检定级项目，看项目描述和论文研究方向比较匹配场景，是否方便留个联系方式具体沟通，看能不能合作。

**Comment by zichengzichengzi** [comment]
qq：1079105180

**Comment by zichengzichengzi** [comment]
> 你好，我这边当前也是在做废钢回收场景的质检定级项目，看项目描述和论文研究方向比较匹配场景，是否方便留个联系方式具体沟通，看能不能合作。

qq：1079105180
